[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["python -m ensurepip --upgrade", "pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'No build step needed for Python'"]

[start]
cmd = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
