[phases.setup]
nixPkgs = ["python39", "nodejs", "npm", "pip"]

[phases.install]
cmds = [
  "cd backend && pip install -r requirements.txt",
  "cd frontend && npm ci"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "bash start.sh"
