"""Add AI conversation tables

Revision ID: e395c9cc6540
Revises: 182682f16ed6
Create Date: 2025-10-04 18:52:18.324524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e395c9cc6540'
down_revision: Union[str, None] = '182682f16ed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversations_id'), 'ai_conversations', ['id'], unique=False)
    op.create_table('ai_conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('pet_context', sa.JSON(), nullable=True),
    sa.Column('suggested_actions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_conversation_messages_id'), 'ai_conversation_messages', ['id'], unique=False)
    op.drop_table('provider_services_link')
    op.drop_index(op.f('ix_service_types_id'), table_name='service_types')
    op.drop_table('service_types')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_types',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('service_types_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='service_types_pkey'),
    sa.UniqueConstraint('name', name='service_types_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_service_types_id'), 'service_types', ['id'], unique=False)
    op.create_table('provider_services_link',
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('provider_services_link_provider_id_fkey')),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], name=op.f('provider_services_link_service_type_id_fkey')),
    sa.PrimaryKeyConstraint('provider_id', 'service_type_id', name=op.f('provider_services_link_pkey'))
    )
    op.drop_index(op.f('ix_ai_conversation_messages_id'), table_name='ai_conversation_messages')
    op.drop_table('ai_conversation_messages')
    op.drop_index(op.f('ix_ai_conversations_id'), table_name='ai_conversations')
    op.drop_table('ai_conversations')
    # ### end Alembic commands ###
